[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "docker-data-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.26.0",
]


[project.scripts]
validate = "scripts.validate:main"

[tool.setuptools]
packages = ["scripts"]

[dependency-groups]
dev = [
    "basedpyright>=1.39.3",
    "ruff>=0.15.12",
]
